version: '3'

tasks:
  run-demo:
    desc: Build and run the demo
    dir: demos/demo
    cmds:
      - go build -o ../bin/viewty
      - ../bin/viewty
      - cat viewty.log

  test:
    desc: Run all tests
    cmds:
      - go test -v -cover
