package action

var bufdefaults = map[string]string{
	"Up":             "CursorUp",
	"Down":           "CursorDown",
	"Right":          "CursorRight",
	"Left":           "CursorLeft",
	"ShiftUp":        "SelectUp",
	"ShiftDown":      "SelectDown",
	"ShiftLeft":      "SelectLeft",
	"ShiftRight":     "SelectRight",
	"CtrlLeft":       "WordLeft",
	"CtrlRight":      "WordRight",
	"AltUp":          "MoveLinesUp",
	"AltDown":        "MoveLinesDown",
	"CtrlShiftRight": "SelectWordRight",
	"CtrlShiftLeft":  "SelectWordLeft",
	"AltLeft":        "StartOfTextToggle",
	"AltRight":       "EndOfLine",
	"AltShiftLeft":   "SelectToStartOfTextToggle",
	"ShiftHome":      "SelectToStartOfTextToggle",
	"AltShiftRight":  "SelectToEndOfLine",
	"ShiftEnd":       "SelectToEndOfLine",
	"CtrlUp":         "CursorStart",
	"CtrlDown":       "CursorEnd",
	"CtrlShiftUp":    "SelectToStart",
	"CtrlShiftDown":  "SelectToEnd",
	"Alt-{":          "ParagraphPrevious",
	"Alt-}":          "ParagraphNext",
	"Enter":          "InsertNewline",
	"CtrlH":          "Backspace",
	"Backspace":      "Backspace",
	"OldBackspace":   "Backspace",
	"Alt-CtrlH":      "DeleteWordLeft",
	"Alt-Backspace":  "DeleteWordLeft",
	"Tab":            "IndentSelection|InsertTab",
	"Backtab":        "OutdentSelection|OutdentLine",
	"Alt-[":          "DiffPrevious|CursorStart",
	"Alt-]":          "DiffNext|CursorEnd",
	"Ctrl-z":         "Undo",
	"Ctrl-y":         "Redo",
	"Ctrl-c":         "Copy|CopyLine",
	"Ctrl-x":         "Cut|CutLine",
	"Ctrl-k":         "CutLine",
	"Ctrl-d":         "Duplicate|DuplicateLine",
	"Ctrl-v":         "Paste",
	"Ctrl-a":         "SelectAll",
	"Home":           "StartOfTextToggle",
	"End":            "EndOfLine",
	"CtrlHome":       "CursorStart",
	"CtrlEnd":        "CursorEnd",
	"PageUp":         "CursorPageUp",
	"PageDown":       "CursorPageDown",
	"ShiftPageUp":    "SelectPageUp",
	"ShiftPageDown":  "SelectPageDown",
	"Ctrl-r":         "ToggleRuler",
	"Delete":         "Delete",
	"Insert":         "ToggleOverwriteMode",

	// Emacs-style keybindings
	"Alt-f": "WordRight",
	"Alt-b": "WordLeft",
	"Alt-a": "StartOfText",
	"Alt-e": "EndOfLine",
	// "Alt-p": "CursorUp",
	// "Alt-n": "CursorDown",

	"Esc": "Escape,Deselect,RemoveAllMultiCursors",

	// Mouse bindings
	"MouseWheelUp":     "ScrollUp",
	"MouseWheelDown":   "ScrollDown",
	"MouseLeft":        "MousePress",
	"MouseLeftDrag":    "MouseDrag",
	"MouseLeftRelease": "MouseRelease",
	"MouseMiddle":      "PastePrimary",
	"Ctrl-MouseLeft":   "MouseMultiCursor",

	"Alt-n":        "SpawnMultiCursor",
	"Alt-m":        "SpawnMultiCursorSelect",
	"AltShiftUp":   "SpawnMultiCursorUp",
	"AltShiftDown": "SpawnMultiCursorDown",
	"Alt-p":        "RemoveMultiCursor",
	"Alt-c":        "RemoveAllMultiCursors",
	"Alt-x":        "SkipMultiCursor",
}
